server:
  port: 7901
eureka:
  client:
    healthcheck:
        enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  #false注册名或者true注册ip
  instance:
    prefer-ip-address: false
spring:
  application:
    name: movie
