drop table user if EXISTS ;
create table user(
  id bigint generated by DEFAULT  as IDENTITY ,
  username VARCHAR (40) ,
  name VARCHAR (20),
  age int(3),
  balance DECIMAL (20,2),
  PRIMARY key(id)
  );